services:
  web:
    image: licariri:latest
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    environment:
      - TZ=Europe/Bucharest
      - NODE_ENV=production
      - ALLOW_QUERY_ROUTES=false
      - ALLOW_ADMIN_ROUTES=true
