[nginx-botsearch]
enabled = true
banaction = ufw
filter = nginx-botsearch
logpath = /var/log/nginx/access.log*
findtime = 24h
maxretry = 2
bantime = 4w

[nginx-bad-request]
enabled = true
banaction = ufw
filter = nginx-bad-request
logpath = /var/log/nginx/access.log*
findtime = 24h
maxretry = 2
bantime = 4w
